# Generated by Django 2.0.6 on 2019-11-16 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_auto_20191116_1124'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderinfo',
            options={'ordering': ['-order_sn'], 'verbose_name': '充值订单', 'verbose_name_plural': '充值订单'},
        ),
    ]
