# Generated by Django 2.0.6 on 2019-11-16 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_auto_20191116_1233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderinfo',
            name='user',
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='username',
            field=models.CharField(default='None', max_length=128),
        ),
    ]
