# Generated by Django 2.0.6 on 2019-11-16 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_auto_20191116_1311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='sex',
        ),
        migrations.AddField(
            model_name='user',
            name='dept',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='pay_status',
            field=models.CharField(choices=[('TRADE_SUCCESS', '交易支付成功'), ('TRADE_CLOSED', '未付款交易超时关闭'), ('WAIT_BUYER_PAY', '交易创建'), ('TRADE_FINISHED', '交易结束'), ('PAYING', '待支付')], default='paying', max_length=40, verbose_name='订单状态'),
        ),
    ]
