# Generated by Django 2.0.6 on 2019-11-17 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_auto_20191116_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(default='None', max_length=11, unique=True),
        ),
    ]
