# Generated by Django 2.0.6 on 2019-12-15 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_auto_20191117_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='send_state',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='user',
            name='updated_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
