# Generated by Django 2.0.6 on 2020-02-04 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=128, null=True)),
                ('send_time', models.DateTimeField(auto_now_add=True)),
                ('message', models.CharField(default='None', max_length=128)),
                ('sended', models.BooleanField(default=False)),
            ],
        ),
    ]
