# Generated by Django 2.0.6 on 2019-11-14 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher', models.CharField(max_length=128)),
                ('receiver', models.CharField(max_length=128)),
                ('deadline', models.DateTimeField(verbose_name='deadline')),
                ('pub_time', models.DateTimeField(auto_now_add=True)),
                ('task_detail', models.CharField(max_length=300)),
                ('task_state', models.CharField(choices=[('not_stared', '未开始'), ('processing', '进行中'), ('abort', '中止'), ('revoke', '撤销'), ('timeout', '超时'), ('completed', '完成')], default='未开始', max_length=32)),
            ],
            options={
                'verbose_name': '任务',
                'verbose_name_plural': '用户',
                'ordering': ['pub_time'],
            },
        ),
    ]
