# Generated by Django 2.0.6 on 2019-11-14 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_platform', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['pub_time'], 'verbose_name': '任务', 'verbose_name_plural': '任务'},
        ),
    ]
