# Generated by Django 2.0.6 on 2019-11-25 01:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('task_platform', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user_task',
            options={'ordering': ['pub_time'], 'verbose_name': '用户任务报价', 'verbose_name_plural': '用户任务报价'},
        ),
        migrations.AddField(
            model_name='user_task',
            name='pub_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
