# Generated by Django 2.0.6 on 2019-11-25 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_platform', '0002_auto_20191125_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_task',
            name='submit_money',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
