# Generated by Django 2.0.6 on 2019-11-14 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_platform', '0002_auto_20191114_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_decription',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
