# Generated by Django 2.0.6 on 2019-11-14 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_platform', '0003_task_task_decription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='task_decription',
            new_name='task_description',
        ),
    ]
