# Generated by Django 2.0.6 on 2019-11-14 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_platform', '0004_auto_20191114_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_state',
            field=models.CharField(choices=[('未开始', 'waitting'), ('进行中', 'processing'), ('中止', 'abort'), ('撤销', 'revoke'), ('超时', 'timeout'), ('完成', 'completed')], default='未开始', max_length=32),
        ),
    ]
