# Generated by Django 2.0.6 on 2019-11-17 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_platform', '0005_auto_20191114_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='expected_time_consuming',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='task',
            name='people_needed',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='task',
            name='people_now',
            field=models.IntegerField(default=0),
        ),
    ]
