# Generated by Django 2.0.6 on 2019-12-02 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_platform', '0005_auto_20191201_2139'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task_receive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.IntegerField(default='0')),
                ('username', models.CharField(default='None', max_length=128)),
            ],
            options={
                'verbose_name': '用户任务接受',
                'verbose_name_plural': '用户任务接受',
            },
        ),
    ]
