# Generated by Django 2.0.6 on 2019-11-17 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_platform', '0006_auto_20191117_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='receiver',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
