# Generated by Django 2.0.6 on 2019-11-18 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_platform', '0007_auto_20191117_2259'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task_tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sig_tag', models.CharField(default='None', max_length=20)),
                ('task_id', models.IntegerField(default='0')),
            ],
            options={
                'verbose_name': '任务标签',
                'verbose_name_plural': '任务标签',
            },
        ),
    ]
