# Generated by Django 2.0.6 on 2019-12-05 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_platform', '0008_task_receive_done_money'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_receive',
            name='is_abort',
            field=models.BooleanField(default=False),
        ),
    ]
