# Generated by Django 2.0.6 on 2019-11-18 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_platform', '0008_task_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='deadline',
        ),
    ]
