# Generated by Django 2.0.6 on 2019-12-05 14:04

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_platform', '0009_task_receive_is_abort'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chatinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.CharField(blank=True, max_length=32, null=True)),
                ('task_id', models.IntegerField(blank=True, null=True)),
                ('message', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('send_time', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '聊天信息',
                'verbose_name_plural': '聊天信息',
                'ordering': ['send_time'],
            },
        ),
    ]
