# Generated by Django 2.0.6 on 2019-11-18 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_platform', '0009_remove_task_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='receiver',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
