# Generated by Django 2.0.6 on 2019-12-05 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_platform', '0010_chatinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatinfo',
            name='sender',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
