# Generated by Django 2.0.6 on 2019-11-20 03:25

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_platform', '0010_auto_20191118_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_description',
            field=ckeditor.fields.RichTextField(default='None', max_length=50),
        ),
    ]
