# Generated by Django 2.0.6 on 2019-12-05 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_platform', '0011_chatinfo_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatinfo',
            name='send_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
