# Generated by Django 2.0.6 on 2019-11-20 03:35

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_platform', '0011_auto_20191120_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_description',
            field=ckeditor.fields.RichTextField(default='None'),
        ),
    ]
