# Generated by Django 2.0.6 on 2019-11-20 06:31

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_platform', '0012_auto_20191120_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='None'),
        ),
    ]
