# Generated by Django 2.0.6 on 2019-12-06 02:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('task_platform', '0012_auto_20191205_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatinfo',
            name='send_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 6, 2, 30, 57, 777067, tzinfo=utc)),
        ),
    ]
