# Generated by Django 2.0.6 on 2019-11-24 11:05

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_platform', '0013_auto_20191120_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_description',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_detail',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='None'),
        ),
    ]
