# Generated by Django 2.0.6 on 2019-12-12 00:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('task_platform', '0014_auto_20191206_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatinfo',
            name='send_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 12, 0, 41, 11, 347910, tzinfo=utc)),
        ),
    ]
