# Generated by Django 2.2.7 on 2019-12-12 10:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_platform', '0015_auto_20191212_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatinfo',
            name='send_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 12, 10, 31, 3, 736358)),
        ),
    ]
