# Generated by Django 2.0.6 on 2019-12-12 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_platform', '0015_auto_20191212_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatinfo',
            name='send_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
