# Generated by Django 2.2.7 on 2019-12-12 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_platform', '0016_auto_20191212_1031'),
        ('task_platform', '0016_auto_20191212_1635'),
    ]

    operations = [
    ]
