# Generated by Django 2.0.6 on 2019-12-13 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_platform', '0017_merge_20191212_1828'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatVision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.CharField(blank=True, max_length=32, null=True)),
                ('username', models.CharField(max_length=128)),
                ('has_seen', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '消息查看',
                'verbose_name_plural': '消息查看',
                'ordering': ['has_seen'],
            },
        ),
        migrations.AlterField(
            model_name='chatinfo',
            name='send_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
