# Generated by Django 2.0.6 on 2019-12-15 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_platform', '0018_auto_20191213_2345'),
    ]

    operations = [
        migrations.CreateModel(
            name='Withdraw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=128, null=True)),
                ('img_path', models.CharField(blank=True, max_length=256, null=True)),
                ('money', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('state', models.CharField(blank=True, choices=[('发起', 'start'), ('完成', 'complete'), ('取消', 'cancel')], max_length=20, null=True)),
                ('noticed', models.BooleanField(default=False)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '提现记录',
                'verbose_name_plural': '提现记录',
                'ordering': ['-start_time'],
            },
        ),
    ]
