# Generated by Django 2.0.6 on 2019-12-16 10:04

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_platform', '0020_auto_20191215_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdraw',
            name='img_path',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
